{
  "5777368728cab34aec99bce292e15e60" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "3339a57db2b1f03f",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9AD7040>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882824627,
        "stop" : 1646882845657,
        "duration" : 21030
      }
    } ]
  },
  "9b58e419aa66c81ba5e26368887473ad" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "1915cdf51f1e433f",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/user?current=1&pageSize=100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9977790>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882803461,
        "stop" : 1646882824507,
        "duration" : 21046
      }
    } ]
  },
  "e48abca8fb0895e685397860fb6393f1" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "e0c410a593324e2d",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"id\":<built-in function id>}\n          ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882824609,
        "stop" : 1646882824611,
        "duration" : 2
      }
    } ]
  },
  "b0878ee5eb70538305b060fabbf99fe0" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "bc827f2f21960525",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"ids\":[${roleId1}]}\n            ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882972633,
        "stop" : 1646882972635,
        "duration" : 2
      }
    } ]
  },
  "94c53f645702c06e17118fd92e09f479" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "750b39748b5c6fa7",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"username\":\"${username}1\",\"roleIds\":[${roleId}],\"id\":\"<built-in function id>\"}\n                                          ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882824591,
        "stop" : 1646882824592,
        "duration" : 1
      }
    } ]
  },
  "cb8576f098f00f7b2b9caa91976f2b58" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "e39f4a6531161c71",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/role (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9D10FA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882888067,
        "stop" : 1646882909122,
        "duration" : 21055
      }
    } ]
  },
  "0d3dd93f9d173bd3e59f983349bd1202" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "88bf0bc3e10af1fa",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"ids\":[${id2}, ${id3}]}\n            ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882845760,
        "stop" : 1646882845762,
        "duration" : 2
      }
    } ]
  },
  "5a1a59aa4470006c7c58a5ba625a4478" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "d25866acda1875d9",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/roles (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9A98850>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882845778,
        "stop" : 1646882866825,
        "duration" : 21047
      }
    } ]
  },
  "b38dd9102eca0ecc435403cc70874ea0" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "b601d07ca6863b88",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"id\":${roleId1}}\n          ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882972614,
        "stop" : 1646882972616,
        "duration" : 2
      }
    } ]
  },
  "d5345d39adc3d02ffcaf8f15af49ab18" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "258532dd16e22554",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/roleList (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9BA8760>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882782231,
        "stop" : 1646882803265,
        "duration" : 21034
      }
    } ]
  },
  "8174f8ecb1004db16679a852ff5f760a" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "edd352dc044201ca",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D98CE310>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882760884,
        "stop" : 1646882781931,
        "duration" : 21047
      }
    } ]
  },
  "606664f28e2ceb44b0ad0dc80a135fc2" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "bb684e0c90483270",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/role (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9B36490>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882909207,
        "stop" : 1646882930247,
        "duration" : 21040
      }
    } ]
  },
  "0739167ffd7bddb403117cdf6fcb588f" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "ccde792846b0d225",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"username\":\"new_adminy\",\"password\":\"123456\",\"roleIds\":[${roleId}]}\n                                                            ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882803442,
        "stop" : 1646882803444,
        "duration" : 2
      }
    } ]
  },
  "371500b22dde43facb97f8752bf0ff77" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "17bf693613d5028b",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"ids\":[${roleId2},${roleId3}]}\n            ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882972652,
        "stop" : 1646882972654,
        "duration" : 2
      }
    } ]
  },
  "2a3dfa6b36ee5ab01504c51319b8492e" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "53dcca12b1c2df87",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/role (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9B63580>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882951483,
        "stop" : 1646882972529,
        "duration" : 21046
      }
    } ]
  },
  "25f6ba9e78828713a480fcdbed4cfa82" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "f0743a6355e6d1a",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"ids\":[<built-in function id>]}\n            ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882845742,
        "stop" : 1646882845743,
        "duration" : 1
      }
    } ]
  },
  "d9a0d8b349872450f96c814afdee344e" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "c915e5a01aa80bd7",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/role (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9B35A60>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882866925,
        "stop" : 1646882887980,
        "duration" : 21055
      }
    } ]
  },
  "5dcd673c9103656bd9a03aaad715fda7" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "4fa907ace59f1cc9",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.8.253', port=80): Max retries exceeded with url: /api/userMgr/roles (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3D9D39820>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1646882930347,
        "stop" : 1646882951399,
        "duration" : 21052
      }
    } ]
  },
  "3a098e261ee7b9115a8be890393002aa" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "61088bd009f1033b",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"username\":\"new_admin\",\"password\":\"123456\",\"roleIds\":[${roleId}]}\n                                                           ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882803353,
        "stop" : 1646882803354,
        "duration" : 1
      }
    } ]
  },
  "f9a3a528aa08d345b131e068670a2332" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "69a79cf8f8a47f19",
      "status" : "broken",
      "statusDetails" : "  File \"<string>\", line 1\n    {\"username\":\"new_adminx\",\"password\":\"123456\",\"roleIds\":[${roleId}]}\n                                                            ^\nSyntaxError: invalid syntax",
      "time" : {
        "start" : 1646882803411,
        "stop" : 1646882803413,
        "duration" : 2
      }
    } ]
  }
}